## lugemine
GET http://localhost:3035/api/tood

### saatmine
POST http://localhost:3035/api/tood
Content-Type: application/json

{
   "nimetus": "Uute andmete 2 sisestamine",
   "prioriteet": "keskmine",
   "kasTehtud": true
}

### taski eemaldamine
DELETE  http://localhost:3035/api/too